name: Python File Commit Trigger

on:
  push:
    paths:
      - '**/*.py'

jobs:
  get-bearer-token:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Bearer Token
        id: get_token
        run: |
          response=$(curl --location --request POST 'https://idm.stackspot.com/stackspot/oidc/oauth/token' \
          --header 'Content-Type: application/x-www-form-urlencoded' \
          --data-urlencode 'client_id=f4096bfc-7f7c-4401-806f-411b19bd0959' \
          --data-urlencode 'grant_type=client_credentials' \
          --data-urlencode 'client_secret=1I61F1M93LMS7mElqDacgyD7NSYtv4s6xC854f7IhMvF6OrJ5Cic5wzvwW2I3IX8')
          echo "response="
          token=$(echo  | jq -r '.access_token')
          echo "::set-output name=token::"

  execute-quick-command:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: RQC1-post
        id: execute_rqc
        run: |
          token="${{ steps.get_token.outputs.token }}"
          response=$(curl -s -o response_body.txt -w "%{http_code}" -X POST "https://genai-code-buddy-api.stackspot.com/v1/quick-commands/create-execution/is-it-vulnerable" \
          -H "Authorization: Bearer " \
          -H "Content-Type: application/json" \
          -d "{\"input_data\": \"Hi, how are you? This is an example of how to create Remote Quick Command.\"}")
          status_code=$(echo  | tail -n1)
          response_body=$(cat response_body.txt)
          echo "status_code="
          echo "response_body="
          echo "::set-output name=status_code::"
          echo "::set-output name=api_response::"

      - name: Check API Response Status
        run: |
          if [ "${{ steps.execute_rqc.outputs.status_code }}" -eq 200 ]; then
            echo "Request was successful!"
          else
            echo "Request failed with status code ${{ steps.execute_rqc.outputs.status_code }}"
            exit 1
          fi

      - name: Display API Response
        run: |
          echo "API Response: ${{ steps.execute_rqc.outputs.api_response }}"